name: baocao
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.0.0 # Đã chỉnh lại để tương thích tốt hơn với nhiều máy

dependencies:
  flutter:
    sdk: flutter

  # Icon của iOS
  cupertino_icons: ^1.0.8
  
  # Thư viện vẽ biểu đồ (Pie Chart)
  fl_chart: ^0.68.0 
  
  # Thư viện gọi API
  http: ^1.2.1

  # --- QUAN TRỌNG: Thư viện format tiền tệ ---
  intl: ^0.19.0
  # -------------------------------------------

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # Đảm bảo bạn đã tạo thư mục này và bỏ ảnh vào
  assets:
    - assets/images/