name: baocao
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
<<<<<<< HEAD
  sdk: ^3.9.2
=======
  sdk: ^3.0.0 # Đã chỉnh lại để tương thích tốt hơn với nhiều máy
>>>>>>> backend-dev

dependencies:
  flutter:
    sdk: flutter

<<<<<<< HEAD
  cupertino_icons: ^1.0.8
  
  # Thư viện để vẽ biểu đồ tròn
  fl_chart: ^0.70.0
=======
  # Icon của iOS
  cupertino_icons: ^1.0.8
  
  # Thư viện vẽ biểu đồ (Pie Chart)
  fl_chart: ^0.68.0 
  
  # Thư viện gọi API
  http: ^1.2.1

  # --- QUAN TRỌNG: Thư viện format tiền tệ ---
  intl: ^0.19.0
  # -------------------------------------------
>>>>>>> backend-dev

dev_dependencies:
  flutter_test:
    sdk: flutter

<<<<<<< HEAD
  flutter_lints: ^5.0.0
=======
  flutter_lints: ^3.0.0
>>>>>>> backend-dev

flutter:
  uses-material-design: true

<<<<<<< HEAD
  # Đảm bảo đường dẫn assets của bạn chính xác
=======
  # Đảm bảo bạn đã tạo thư mục này và bỏ ảnh vào
>>>>>>> backend-dev
  assets:
    - assets/images/